cirro:
  agent:
    url: https://app.cirro.bio
    id: default-agent
    heartbeat-interval: 60
    watch-interval: 2
    log-level: INFO
    work-directory: work/
    version: '@BUILD_VERSION@'
    shared-directory: shared/
    jwt-expiry-days: 7
