cirro:
  agent:
    url: https://app.cirro.bio
    id: default-agent
    heartbeat-interval: 60
    watch-interval: 2
    log-level: INFO
    work-directory: work/
    version: 0.1.0
    scripts-directory: scripts/
