cirro:
  agent:
    url: https://app.cirro.bio
    id: default-agent
    endpoint: http://localhost:8080
    heartbeat-interval: 60
    watch-interval: 10
    log-level: INFO
    work-directory: work/
    version: '@BUILD_VERSION@'
    shared-directory: shared/
    jwt-expiry-days: 7
    submit-script-name: submit_headnode.sh
    stop-script-name: stop_headnode.sh
micronaut:
  http:
    client:
      read-timeout: 15s
datasources:
  default:
    url: "jdbc:h2:mem:;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
    dialect: H2
    schema-generate: CREATE
