cirro:
  agent:
    url: https://app.cirro.bio
    id: default-agent
    heartbeat-interval: 60
    watch-interval: 10
    log-level: INFO
    work-directory: work/
    version: '@BUILD_VERSION@'
    shared-directory: shared/
    jwt-expiry-days: 7
    submit-script-name: submit_headnode.sh
    stop-script-name: stop_headnode.sh
