name: Build and Upload Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Run build with Gradle Wrapper
      run: ./gradlew shadowJar nativeCompile

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: agent-jar
        path: build/libs/*.jar

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: agent-native
        path: build/native/nativeCompile/cirro-agent*

