name: Build and push docker image

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        native-image-job-reports: 'true'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Run build with Gradle Wrapper
      run: |
        export BUILD_VERSION=$(date +'%Y%m%d')-$GITHUB_REF_NAME
        ./gradlew dockerBuildNative

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to GitHub Container Registry
      run: |
        export BUILD_VERSION=$(date +'%Y%m%d')-${GITHUB_REF_NAME}
        docker tag cirro-agent ghcr.io/cirrobio/cirro-local-agent:${BUILD_VERSION}
        docker tag cirro-agent ghcr.io/cirrobio/cirro-local-agent:${GITHUB_REF_NAME}
        docker tag cirro-agent ghcr.io/cirrobio/cirro-local-agent:${GITHUB_SHA::7}
        docker tag cirro-agent ghcr.io/cirrobio/cirro-local-agent:latest
        docker push --all-tags ghcr.io/cirrobio/cirro-local-agent
