name: Build and push docker image

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        native-image-job-reports: 'true'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Run build with Gradle Wrapper
      run: |
        export BUILD_VERSION=$(date +'%Y%m%d')-$GITHUB_REF_NAME
        ./gradlew shadowJar

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        push: true
        tags: |
          ghcr.io/cirrobio/cirro-local-agent:latest
          ghcr.io/cirrobio/cirro-local-agent:${{ env.GITHUB_REF_NAME }}
        labels: |
          org.opencontainers.image.title=cirro-local-agent
          org.opencontainers.image.description=Cirro Agent
          org.opencontainers.image.url=https://github.com/CirroBio/Cirro-local-agent
